# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 716a71cc9788419f69227dd5fa8ec550fbe3c95498b83015cf68656ba7cbbac2526c4232170e1f419cd6f7faeb7ec7dab21a536ee125bfce01dcc39c1ae60303

test:
  secret_key_base: 911394db31794f6526760fab0c99604af32bf07ccaa579b4cfcf8651e3878d72dc0b2d84c7e9ca5b5d103bc1e81eb26295cd2f1b7f1db08ac8a85a2681c26c56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
